### ISSUE TITLE
Prevent replacement of apostrophes with html character entities

### ISSUE THREAD

**Issue by vglaeser** [daniel-sc/xliff-simple-merge#4]
Currently, apostrophes ( ' ) in xliff-files in `<source>` or `<target>` tags will be replaced by `&apos;` when running xliff-simple-merge.
Is there a way to prevent this behaviour?
Thanks in advance

**Comment by daniel-sc** [comment]
Hi @vglaeser 

Currently this behavior cannot be changed.

I think that converting `'` to `&apos;` leads to conform XML (which Xliff is base upon). At least in the [spec for XLIFF 1.0](https://www.oasis-open.org/committees/xliff/documents/contribution-xliff-20010530.htm) this is explicitly mentioned. To my knowledge this is well handled by the angular translations merge step in the build.

So I'd suggest that this is not really a problem - but please convince me otherwise and I'll look for a solution :)

**Comment by vglaeser** [comment]
Hi @daniel-sc ,
thank you for your fast response.
Indeed, it seems to be part of the specification, althouth it doesn't seem to be required to be replaced, at least `ng extract-i18n` doesn't replace `'` by `&apos`.
In our case we are sending the generated xliff-files to our customer who redirects changed entries to a translator.
In order to avoid problems with our customer's change-detection it would be nice if we could disable the replacement but if necessary we could also use a script in order to replace characters in xliff-files.

**Comment by daniel-sc** [comment]
Hi @vglaeser, I understand - please try v0.7.0 with the new configuration `--no-replace-apostrophe` :)

**Comment by vglaeser** [comment]
Thank you, this is working like a charm
